version: '3'
services:
  db:
   image: influxdb:1.2.4
  api:
    build:
      context: .
    command: /bin/sh -c 'curl -i -XPOST http://db:8086/query --data-urlencode "q=CREATE DATABASE iot" && npm test' 