version: "3.1"
services:
  db:
    image: influxdb:1.2.4
    command: -config /etc/influxdb/influxdb.conf
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdata:/var/lib/influxdb
  api:
    image: bkake/iot-api:v1
    build: .
    command: npm start
    ports:
      - 1337:1337
  dashbord:
    image: grafana/grafana
    ports: 
      - 3000:3000    
volumes:
  influxdata: