# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    db:
      - image: influxdb:1.2.4
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: /bin/sh -c 'curl -i -XPOST http://db:8086/query --data-urlencode "q=CREATE DATABASE iot" && npm test'

  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      # Docker is preinstalled, along with docker-compose
      - checkout
    steps:
      - run: |
         docker build --rm=false -t bkake/iot-api:$CIRCLE_BRANCH .
         docker tag bkake/iot-api:$CIRCLE_BRANCH bkake/iot-api:$CIRCLE_SHA1
         docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
         docker push bkake/iot-api:$CIRCLE_BRANCH
